name: connectanum_dart
version: 1.0.0-alpha.1
description: >-
  This projects implements the wamp protocol with some advanced features. It uses dart streams to make the code reactive.
  The major goal is to make it easy to use, extend and test and make it easy to test implementations that use this package.
dependencies:
  pointycastle: ^1.0.2
  logging: 0.11.4
dev_dependencies:
  test: ^1.11.0