name: connectanum
authors:
  - Richard Burkhardt <my.richidd@gmail.com>
homepage: https://github.com/konsultaner/connectanum-dart
version: 1.0.0-dev.6
description: >-
  This is a WAMP client (Web Application Messaging Protocol) implementation for the dart language and flutter projects.
dependencies:
  pointycastle: ^1.0.2
  logging: ^0.11.4
dev_dependencies:
  test: ^1.12.0
  stream_channel: 2.0.0
environment:
  sdk: ">=2.1.0 <3.0.0"
